export interface Policies {
  policyId:string,
  folio:string,
  folioOT: string,
  insuranceId: string,
  insuranceCompany: string,
  branchId: string,
  subBranchId: string,
  noPolicy: string,
  endorsement: number,
  agentNumber:string,
  renewablePolicy: true,
  issuanceDate: string,
  startValidity: string,
  endValidity: string,
  currency: string,
  paymentMethod: string,
  collectionMethod: string,
  paymentFrequency:string,
  clientId: string,
  clientName: string,
  rfc: string,
  street: string,
  neighborhood: string,
  state: number,
  municipality: number,
  locality: number;
  zip: number,
  country: string,
  salesPerson: string,
  beneficiaryFolio:string,
  coveragePackageFolio:string,
  groups:string,
  comments:string,
  netPremium: number,
  settingOne: number,
  settingTwo: number,
  rights: number,
  financing: number,
  financingPercentage:number,
  iva: string,
  totalPremium: string,
  additionalCharge:number,
  subtotal: number,
  receipts: number,
  commissionPercentage:number,
  policyStatusFolio:string,
  policyStatusDescription: string,
  objectStatusId: number,
  concept: string,
  health: number,
  classification?: string,
  surcharge?:number,
  vehiclePolicy?: any[],
  personPolicie?: any[],
}

export default Policies;
